### ISSUE TITLE
Building on Arch Linux

### ISSUE THREAD

**Issue by jersobh** [innovate-technologies/DJ#12]
Hi there,

I've got this error while trying to "make":

[jeff@jeff-maxcast DJ-master]$ make
rm -rf tmp-armhf
mkdir tmp-armhf
cp Dockerfile tmp-armhf/Dockerfile
cp -rf src tmp-armhf/
for arch in amd64 armhf; do                     \
  if [ "$arch" != "armhf" ]; then       \
    sed -i "/arch=$arch/d" tmp-armhf/Dockerfile;              \
  fi;                                        \
done
sed -i '/#[[:space:]]*arch=armhf/s/^#//' tmp-armhf/Dockerfile
sed -i 's/#[[:space:]]*arch=armhf//g' tmp-armhf/Dockerfile
cat tmp-armhf/Dockerfile
FROM meyskens/ubuntu-multiarch:armhf-xenial 

RUN apt-get update && apt-get -y upgrade && apt-get -y install git sudo curl unattended-upgrades python build-essential && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && apt-get -f -y install nodejs

COPY ./src /dj
RUN cd /dj && npm install
ENV username=""
ENV DEBUG="true"
#ENV compiled="true"

EXPOSE 80

CMD cd /dj/bin && node app.js
docker build --no-cache -t innovate/dj:armhf-latest tmp-armhf
Sending build context to Docker daemon 39.85 MB
Step 1/8 : FROM meyskens/ubuntu-multiarch:armhf-xenial
 ---> 36ac8d11be2a
Step 2/8 : RUN apt-get update && apt-get -y upgrade && apt-get -y install git sudo curl unattended-upgrades python build-essential && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && apt-get -f -y install nodejs
 ---> Running in a5923ecd24b3
standard_init_linux.go:178: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update && apt-get -y upgrade && apt-get -y install git sudo curl unattended-upgrades python build-essential && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && apt-get -f -y install nodejs' returned a non-zero code: 1
make: *** [Makefile:7: build] Error 1

**Comment by meyskens** [comment]
https://eyskens.me/multiarch-docker-images/ make sure you select the right target architecture. Also you can use it without, the makefile is just used to build the docker container
